config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root 'courses#index'

  resources :courses
  get '/collections/:collection_id/courses/:course_id/belongs_to', to: 'courses#check_membership', as: :check_membership
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_and_belongs_to_many :courses, join_table: :collection_memberships
  has_one :discount

  def largest_discount_percentage
    return 0 unless discount

    discount.amount
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :collections, join_table: :collection_memberships
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  def index
    @courses = filter_courses(Course.all)

    render json: @courses
  end

  # GET /courses/1
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /courses/1
  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /courses/1
  def destroy
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  def check_membership
    begin
      collection = Collection.find(params[:collection_id])
      course = Course.find(params[:course_id])

      belongs_to_collection = collection.courses.exists?(course.id)

      render json: { belongs_to_collection: belongs_to_collection }
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: 'Collection or course not found' }, status: :not_found
    rescue => e
      render json: { error: 'Unexpected error ' }, status: :internal_server_error
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :published)
    end

  def filter_courses(courses)
    if params[:published].present?
      courses.where(published: params[:published])
    else
      courses
    end
  end
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = GraphQlTaskSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.published %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @course.published %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GraphQLTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>